import { useSearch } from '@tanstack/react-router'

import {
  Card,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'

export default function PokemonDatabaseCard() {
  const searchedPokemon = useSearch({
    from: '/',
    select: (search) => search.searchTerm,
  })

  return (
    <article className="grid grid-cols-6 gap-8 mx-8 my-4">
      <Card>
        <CardHeader>
          <img
            src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png"
            alt="Pokemon"
            className="w-full m-auto max-w-[150px]"
          />
          <CardTitle>Bulbasaur</CardTitle>
          <CardDescription>#001</CardDescription>
          <CardDescription>
            <p>GRASS</p>
            <p>POISON</p>
          </CardDescription>
        </CardHeader>
      </Card>
      <Card>
        <CardHeader>
          <img
            src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png"
            alt="Pokemon"
          />
          <CardTitle>Bulbasaur</CardTitle>
          <CardDescription>#001</CardDescription>
          <CardDescription>
            <p>GRASS</p>
            <p>POISON</p>
          </CardDescription>
        </CardHeader>
      </Card>
      <Card>
        <CardHeader>
          <img
            src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png"
            alt="Pokemon"
          />
          <CardTitle>Bulbasaur</CardTitle>
          <CardDescription>#001</CardDescription>
          <CardDescription>
            <p>GRASS</p>
            <p>POISON</p>
          </CardDescription>
        </CardHeader>
      </Card>
      <Card>
        <CardHeader>
          <img
            src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png"
            alt="Pokemon"
          />
          <CardTitle>Bulbasaur</CardTitle>
          <CardDescription>#001</CardDescription>
          <CardDescription>
            <p>GRASS</p>
            <p>POISON</p>
          </CardDescription>
        </CardHeader>
      </Card>
      <Card>
        <CardHeader>
          <img
            src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png"
            alt="Pokemon"
          />
          <CardTitle>Bulbasaur</CardTitle>
          <CardDescription>#001</CardDescription>
          <CardDescription>
            <p>GRASS</p>
            <p>POISON</p>
          </CardDescription>
        </CardHeader>
      </Card>
      <Card>
        <CardHeader>
          <img
            src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png"
            alt="Pokemon"
          />
          <CardTitle>Bulbasaur</CardTitle>
          <CardDescription>#001</CardDescription>
          <CardDescription>
            <p>GRASS</p>
            <p>POISON</p>
          </CardDescription>
        </CardHeader>
      </Card>
      <Card>
        <CardHeader>
          <img
            src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png"
            alt="Pokemon"
            className="w-full m-auto max-w-[150px]"
          />
          <CardTitle>Bulbasaur</CardTitle>
          <CardDescription>#001</CardDescription>
          <CardDescription>
            <p>GRASS</p>
            <p>POISON</p>
          </CardDescription>
        </CardHeader>
      </Card>
      <Card>
        <CardHeader>
          <img
            src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png"
            alt="Pokemon"
          />
          <CardTitle>Bulbasaur</CardTitle>
          <CardDescription>#001</CardDescription>
          <CardDescription>
            <p>GRASS</p>
            <p>POISON</p>
          </CardDescription>
        </CardHeader>
      </Card>
      <Card>
        <CardHeader>
          <img
            src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png"
            alt="Pokemon"
          />
          <CardTitle>Bulbasaur</CardTitle>
          <CardDescription>#001</CardDescription>
          <CardDescription>
            <p>GRASS</p>
            <p>POISON</p>
          </CardDescription>
        </CardHeader>
      </Card>
      <Card>
        <CardHeader>
          <img
            src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png"
            alt="Pokemon"
          />
          <CardTitle>Bulbasaur</CardTitle>
          <CardDescription>#001</CardDescription>
          <CardDescription>
            <p>GRASS</p>
            <p>POISON</p>
          </CardDescription>
        </CardHeader>
      </Card>
      <Card>
        <CardHeader>
          <img
            src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png"
            alt="Pokemon"
          />
          <CardTitle>Bulbasaur</CardTitle>
          <CardDescription>#001</CardDescription>
          <CardDescription>
            <p>GRASS</p>
            <p>POISON</p>
          </CardDescription>
        </CardHeader>
      </Card>
      <Card>
        <CardHeader>
          <img
            src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png"
            alt="Pokemon"
          />
          <CardTitle>Bulbasaur</CardTitle>
          <CardDescription>#001</CardDescription>
          <CardDescription>
            <p>GRASS</p>
            <p>POISON</p>
          </CardDescription>
        </CardHeader>
      </Card>
    </article>
  )
}
